# Generated by Django 6.0.1 on 2026-07-21 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=5)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['bin_id'],
            },
        ),
        migrations.CreateModel(
            name='BinReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_pct', models.FloatField()),
                ('distance_cm', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='bins.bin')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
