# Generated by Django 6.0.7 on 2026-08-11 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_demo_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('district_collector', 'District Collector'), ('municipal', 'Municipal Officer'), ('corporate', 'Corporate Officer'), ('driver', 'Driver')], default='driver', max_length=30)),
                ('zone', models.CharField(blank=True, help_text='Zone/Location this user is restricted to', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
