# Generated by Django 4.2 on 2026-08-11 12:53

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='bins.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='bins.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='bins.municipality')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots', to='bins.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('facility_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='bins.municipality')),
            ],
        ),
        migrations.RenameField(
            model_name='bin',
            old_name='zone',
            new_name='legacy_zone',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='zone',
            new_name='legacy_zone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='legacy_zone',
            field=models.CharField(blank=True, help_text='Legacy zone string', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('municipal_admin', 'Municipal Admin'), ('municipal_officer', 'Municipal Officer'), ('zone_supervisor', 'Zone Supervisor'), ('driver', 'Driver'), ('field_worker', 'Field Worker'), ('auditor', 'Auditor')], default='driver', max_length=30),
        ),
        migrations.AddField(
            model_name='bin',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bins', to='bins.municipality'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bins.municipality'),
        ),
        migrations.AddField(
            model_name='bin',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bins', to='bins.zone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bins.zone'),
        ),
        migrations.AddField(
            model_name='bin',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bins', to='bins.ward'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bins.ward'),
        ),
    ]
