# Generated by Django 6.0.7 on 2026-08-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0005_map_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='legacy_zone',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('COMPACTOR', 'Compactor'), ('TIPPER', 'Tipper'), ('MINI_TRUCK', 'Mini Truck'), ('TRACTOR', 'Tractor'), ('OTHER', 'Other')], default='COMPACTOR', max_length=20)),
                ('capacity', models.FloatField()),
                ('capacity_unit', models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('tons', 'Tons')], default='m3', max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('ON_ROUTE', 'On Route'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='bins.depot')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='bins.userprofile')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='bins.municipality')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='bins.zone')),
            ],
            options={
                'ordering': ['vehicle_id'],
            },
        ),
    ]
