# Generated by Django 6.0.7 on 2026-08-11 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0007_userprofile_date_of_joining_userprofile_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('DISPATCHED', 'Dispatched'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bins', models.ManyToManyField(related_name='schedules', to='bins.bin')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='bins.depot')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_schedules', to='bins.userprofile')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bins.municipality')),
                ('processing_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='bins.processingfacility')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='bins.vehicle')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='bins.ward')),
                ('workers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'field_worker'}, related_name='worked_schedules', to='bins.userprofile')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bins.zone')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='collectionroute',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='bins.collectionschedule'),
        ),
    ]
