# Generated by Django 6.0.7 on 2026-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0008_collectionschedule_collectionroute_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionroute',
            name='end_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectionroute',
            name='estimated_duration_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionroute',
            name='optimization_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='collectionroute',
            name='start_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectionroute',
            name='total_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionroute',
            name='travel_time_available',
            field=models.BooleanField(default=False),
        ),
    ]
