# Generated by Django 6.0.7 on 2026-08-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0009_collectionroute_end_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionroute',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('dispatched', 'Dispatched'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ARRIVED', 'Arrived'), ('COLLECTED', 'Collected'), ('UNABLE_TO_COLLECT', 'Unable to Collect')], default='PENDING', max_length=20)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('exception_reason', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_records', to='bins.bin')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections_performed', to='bins.userprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='bins.collectionroute')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='bins.collectionschedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('schedule', 'bin')},
            },
        ),
    ]
