# Generated by Django 6.0.7 on 2026-08-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0010_alter_collectionroute_status_collectionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_name', models.CharField(default='SYSTEM', help_text='Name of the actor, useful for automated actions without a user', max_length=255)),
                ('role', models.CharField(blank=True, help_text='Role of the user at the time of the action', max_length=50)),
                ('action', models.CharField(choices=[('AUTH_LOGIN', 'Auth Login'), ('AUTH_LOGOUT', 'Auth Logout'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('BIN_CREATED', 'Bin Created'), ('BIN_UPDATED', 'Bin Updated'), ('BIN_DELETED', 'Bin Deleted'), ('ALERT_ACKNOWLEDGED', 'Alert Acknowledged'), ('ALERT_RESOLVED', 'Alert Resolved'), ('VEHICLE_CREATED', 'Vehicle Created'), ('VEHICLE_UPDATED', 'Vehicle Updated'), ('VEHICLE_DEACTIVATED', 'Vehicle Deactivated'), ('STAFF_CREATED', 'Staff Created'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_DEACTIVATED', 'Staff Deactivated'), ('SCHEDULE_CREATED', 'Schedule Created'), ('SCHEDULE_UPDATED', 'Schedule Updated'), ('SCHEDULE_PLANNED', 'Schedule Planned'), ('SCHEDULE_DISPATCHED', 'Schedule Dispatched'), ('SCHEDULE_CANCELLED', 'Schedule Cancelled'), ('ROUTE_GENERATED', 'Route Generated'), ('ROUTE_REGENERATED', 'Route Regenerated'), ('ROUTE_STARTED', 'Route Started'), ('ROUTE_COMPLETED', 'Route Completed'), ('COLLECTION_RECORDED', 'Collection Recorded'), ('COLLECTION_EXCEPTION', 'Collection Exception')], db_index=True, max_length=50)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.CharField(db_index=True, help_text='Identifier of the affected business object', max_length=100)),
                ('changes', models.JSONField(blank=True, help_text='Before and after state of changes', null=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bins.municipality')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bins.userprofile')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bins.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
